### ISSUE TITLE
libEGL warning: DRI2: failed to authenticate

### ISSUE THREAD

**Issue by fatihkunak** [akr3ch/wicker-gui#1]
(zenity:40819): Gtk-WARNING **: 17:53:08.599: Theme parser error: gtk.css:3977:3-22: No property named "-gtk-outline-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4094:3-29: No property named "-GtkWidget-window-dragging"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4108:9-37: No property named "-gtk-outline-top-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4110:9-38: No property named "-gtk-outline-top-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4113:9-40: No property named "-gtk-outline-bottom-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4115:9-41: No property named "-gtk-outline-bottom-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4118:5-33: No property named "-gtk-outline-top-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4120:5-34: No property named "-gtk-outline-top-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4123:5-36: No property named "-gtk-outline-bottom-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.600: Theme parser error: gtk.css:4125:5-37: No property named "-gtk-outline-bottom-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.601: Theme parser error: gtk.css:4131:7-36: No property named "-gtk-outline-top-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.601: Theme parser error: gtk.css:4133:7-39: No property named "-gtk-outline-bottom-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.601: Theme parser error: gtk.css:4136:7-35: No property named "-gtk-outline-top-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.601: Theme parser error: gtk.css:4138:7-38: No property named "-gtk-outline-bottom-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.601: Theme parser error: gtk.css:4212:23-37: Not a valid image

(zenity:40819): Gtk-WARNING **: 17:53:08.601: Theme parser error: gtk.css:4251:3-31: No property named "-gtk-outline-top-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.602: Theme parser error: gtk.css:4253:3-32: No property named "-gtk-outline-top-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.602: Theme parser error: gtk.css:4260:3-34: No property named "-gtk-outline-bottom-left-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.602: Theme parser error: gtk.css:4262:3-35: No property named "-gtk-outline-bottom-right-radius"

(zenity:40819): Gtk-WARNING **: 17:53:08.604: Theme parser error: gtk.css:4930:12-17: "shade" is not a valid color name.

(zenity:40819): Gtk-WARNING **: 17:53:08.604: Theme parser error: gtk.css:4990:12-17: "shade" is not a valid color name.

(zenity:40819): Gtk-WARNING **: 17:53:08.604: Theme parser error: gtk.css:5017:12-15: "mix" is not a valid color name.

(zenity:40819): Gtk-WARNING **: 17:53:08.604: Theme parser error: gtk.css:5021:12-15: "mix" is not a valid color name.

(zenity:40819): Gtk-WARNING **: 17:53:08.605: Theme parser warning: gtk.css:5222:3-5223:1: Expected ';' at end of block

(zenity:40819): Gtk-WARNING **: 17:53:08.605: Theme parser error: gtk.css:5253:3-19: No property named "-gtk-icon-effect"

(zenity:40819): Gtk-WARNING **: 17:53:08.732: Unable to acquire session bus: Failed to execute child process “dbus-launch” (No such file or directory)

**Comment by akr3ch** [comment]
Hi @Neutrale35,

Thank you for submitting the issue. It appears to be related to `zenity`. I am currently investigating and will provide you with an update very soon.

Thanks,
@akr3ch

**Comment by akr3ch** [comment]
Hi @Neutrale35
Thanks for submitting the issue. But, It seems like there are issues with the GTK theme parser and the session bus. To address the theme parser errors, you might need to check or update your GTK theme settings or reinstall the GTK libraries. Regarding the session bus error, make sure D-Bus is installed and running on your system, as it seems the `dbus-launch` command is missing.
